{% set name = "autodynatrace" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/autodynatrace-{{ version }}.tar.gz
  sha256: b503e7c46c67c316a2986f83b96692870d82ac7c9d28df001ea62f7cff9a41a2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - autowrapt >=1.0
    - oneagent-sdk >=1.3.0
    - python >=3.6
    - six >=1.10.0
    - wrapt >=1.11.2

test:
  imports:
    - autodynatrace
    - autodynatrace.wrappers
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dlopes7/autodynatrace
  summary: Auto instrumentation for the OneAgent SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
