{% set name = "autodynatrace" %}
{% set version = "2.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/autodynatrace-{{ version }}.tar.gz
  sha256: 0b75732f541bcb2af57ef87342b238e8cb47b5cc96bcc6fa2ff9d7dfb17ee490

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - autowrapt >=1.0
    - oneagent-sdk >=1.3.0
    - python >={{ python_min }}
    - six >=1.10.0
    - wrapt >=1.11.2

test:
  imports:
    - autodynatrace
    - autodynatrace.wrappers
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/dlopes7/autodynatrace
  summary: Auto instrumentation for the OneAgent SDK
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - janjagusch
